import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="grid place-items-center h-screen">
          <div>
            <h1 className="text-2xl font-bold text-center">
              Welcome to Podlist!
            </h1>
            <p className="text-gray-600 text-center">We're still building!</p>
          </div>
        </div>
      </main>
    </>
  );
}
